POST http://localhost:8080/users
Content-Type: application/json

{
"username":"Victoria",
"email": "weather@gmail.com",
"password": "hi"
}

###

POST http://localhost:8080/users
Content-Type: application/json

{"username":"Erica",
"email": "weather@gmail.com",
"password": "olo" }
###

POST http://localhost:8080/users
Content-Type: application/json

{"username":"I-Yu",
"email": "weather@gmail.com",
"password": "niihao" }

###
PATCH http://localhost:8080/users/1
Content-Type: application/json

{
  "favourites": ["Berlin", "Singapore"]
}

###
DELETE http://localhost:8080/users/1
Content-Type: application/json
