version: '3.7'

services:
  postgres:
    image: "postgres:15.1"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - weather_db_data:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Berlin
      - PGTZ=Europe/Berlin
      - POSTGRES_DB=weather_db
      - POSTGRES_USER=weather_db_user
      - POSTGRES_PASSWORD=passw0rd

volumes:
 weather_db_data: {}